openforcefield/openff-bespokefit

setup.cfg
This PR updates the codecov settings to not include lines which are not expected to be tested, including code within
a `__main__` statement, type checking imports, and `NotImplemented` exceptions.
This PR also adds a new pragma which can be used to explicitly state that blocks of code should be [excluded from the codecov counts](https://coverage.readthedocs.io/en/coverage-4.3.3/excluding.html#excluding-code-from-coverage-py).
=> Exclude not to be tested lines from codecov

openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/tests/conftest.py, openff/bespokefit/tests/optimizers/forcebalance/test_factories.py
This PR refactors the FB target factories to handle the retrieval of QC records in batches, and generalizes the code to potentially expect batches of QC records per target to generate.
=> [GENREF] Refactor FB targets to handle QC records in batches

openff/bespokefit/schema/targets.py, openff/bespokefit/tests/conftest.py
This PR fixes a bug introduced in #21 whereby target models will incorrectly assume that the reference data is bespoke rather than a result collection due to a quirk of how pydantic discriminates `Union` types.
=> Fix target reference data discrimination order

devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml
This PR unpins `pydantic` in the CI environments as the pin is no longer needed.
=> Drop CI pydantic pin

openff/bespokefit/optimizers/forcebalance/factories.py
This PR fixes a potential bug whereby the grid ids included in the `metadata.json` prodcued by the force balance `TorsionProfileTargetFactory` were ordered differently then in `qdata.txt` and `scan.xyz`.
This PR also adds a missed `NotImplementedError` when trying to fit forces using the force balance ab initio target.
=> Fix ordering of grid ids in torsion drive (FB) metadata

openff/bespokefit/fragmentation/fragmenter.py
This PR adds fixed hydrogen InChI identifiers to fragment data which is required since https://github.com/openforcefield/openff-qcsubmit/pull/123.
=> Add fixed hydrogen InChI to fragment data

openff/bespokefit/schema/smirks.py
This PR increases the number of proper torsion terms which may be fit up to 6 (i.e. k1 ... k6), whereas previously only four were allowed.
=> Increase allowed proper torsion terms to six

openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/tests/optimizers/forcebalance/test_factories.py
This PR fixes a typo which caused opt geo target options to be named `optget_options.txt` rather than `optgeo_options.txt` as expected.
=> Fix typo in opt geo target options file name

openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/tests/optimizers/forcebalance/test_factories.py
This PR fixes passing the batch size to FB OptGeo targets as an extra which gets converted to a string by the schema.
=> Fix opt geo batch size passed as extra

openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/tests/optimizers/forcebalance/test_factories.py
This PR fixes a bug whereby if `batch_size` was passed as an extra to an `OptGeo` target it would be included in the `optimize.in` file causing ForceBalance to raise an exception.
The solution implemented here is general and will allow targets to specify which extras should not be included in the target section of the `optimize.in` file.
=> Fix `batch_size` included in target input section

openff/bespokefit/data/templates/force-balance/vibration-target.txt
This PR fixes a typo in the ForceBalance vibration target template whereby `pdb` was used instead of the correct `coords`.
=> Fix pdb typo in FB vibration target template

openff/bespokefit/utilities/provenance.py
This fixes parsing the version of `ambertools` when using `21.0` or later.
=> Retrieve `ambertools` version from conda as backup

devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml, openff/bespokefit/cli/__init__.py, openff/bespokefit/cli/cli.py, openff/bespokefit/cli/prepare.py, openff/bespokefit/tests/cli/conftest.py, openff/bespokefit/tests/cli/test_prepare.py, setup.py
This PR exposes a new `openff-bespoke prepare` CLI:
```
Usage: openff-bespoke prepare [OPTIONS]
Prepare an optimizations' input files based on its schema.
Options:
-i, --input FILE  The file path to a JSON serialized optimization schema.
This can be either a general or a bespoke schema.
--help            Show this message and exit.
```
which is built around the `click` package. Currently if a `bespoke` schema is used as input no QC is spun up and generated when missing, although in future we may consider adding this.
=> Add initial `openff-bespoke prepare` CLI

devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml, openff/bespokefit/fragmentation/__init__.py, openff/bespokefit/fragmentation/base.py, openff/bespokefit/fragmentation/fragmenter.py, openff/bespokefit/fragmentation/model.py, openff/bespokefit/tests/conftest.py, openff/bespokefit/tests/fragmentation/test_fragment_general.py, openff/bespokefit/tests/fragmentation/test_fragmentation.py, openff/bespokefit/tests/schema/bespoke/test_tasks.py, openff/bespokefit/tests/utilities/test_utilities.py, openff/bespokefit/tests/workflows/test_bespoke.py, openff/bespokefit/utilities/__init__.py, openff/bespokefit/utilities/utilities.py, openff/bespokefit/workflows/bespoke.py
This PR updates bespokefit to use the new `openff-fragmenter` package, this simply updates the imports and API calls.
The FragmentEngine attribute `fragmentation_engine` is also renamed to `type` as this is a literal that should not be changed.
=> Openff-Fragmenter update

openff/bespokefit/schema/bespoke/tasks.py, openff/bespokefit/utilities/typing.py
This PR adds a new custom array type for incorporating numpy arrays into pydantic models that replaces the QCElemental implementation. The QCElemental implementation attempts to modify the schema type but does not handle the case of an array of arrays leading to issues when exposing tasks via a RESTful API using FastAPI
=> Add pydantic compatible custom numpy array type

openff/bespokefit/schema/results.py, openff/bespokefit/tests/schema/test_results.py, openff/bespokefit/utilities/smirnoff.py
This PR simplifies the generation of the final forcefield after fitting new bespoke parameters. The old method is now redundant as the new smirks generation method ensures that the parameters are correctly transferred back from the fragment to the parent. We also now just zero out values below the drop out threshold rather than removing them.
=> ForceField generation clean up

devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml, openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/schema/data.py, openff/bespokefit/schema/targets.py, openff/bespokefit/tests/conftest.py, openff/bespokefit/tests/optimizers/forcebalance/test_factories.py, openff/bespokefit/tests/schema/test_data.py
This PR adds a new `LocalQCData` type that allows users to pass QC data generated using QCEngine directly to an input schema.
=> Add support for supplying local QC data

openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/tests/optimizers/forcebalance/test_factories.py
This PR fixes a bug whereby molecules created from `LocalQCData` did not have conformers attached or `grid_ids` in the case of torsion drive data.
=> Fix creating molecule from local QC data

openff/bespokefit/executor/services/coordinator/models.py, openff/bespokefit/schema/results.py, openff/bespokefit/tests/executor/services/coordinator/test_models.py
This PR ensures that the bespoke results are now returned as part of the coordinates get response. It further adds tests of the coordinator models.
=> Add coordinator results to response and model tests

openff/bespokefit/tests/workflows/test_bespoke.py, openff/bespokefit/workflows/bespoke.py
This adds an options to configure the default QC spec(s). Currently this is limited to a single QC spec and no validation is performed to ensure compatibility with the molecule. 
This functionality will be expanded in a future PR to include more rigorous validation + selection of a spec from multiple options.
=> Expose the default QC specs used by the bespoke factory

openff/bespokefit/executor/services/coordinator/models.py, openff/bespokefit/executor/services/fragmenter/models.py, openff/bespokefit/executor/services/optimizer/models.py, openff/bespokefit/executor/services/qcgenerator/models.py, openff/bespokefit/utilities/pydantic.py
This PR fixes a bug whereby the executor response models did not register the custom numpy encoder, and hence could not be dumped to JSON.
=> Fix executor models cannot serialize numpy

devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml, openff/bespokefit/executor/services/fragmenter/worker.py, openff/bespokefit/executor/services/optimizer/worker.py, openff/bespokefit/executor/services/qcgenerator/worker.py, openff/bespokefit/executor/utilities/celery.py
This PR attempts to improve the resilience of celery tasks by acknowledging late. This ensures tasks are passed to other worker if a worker is killed while running a task.
This change requires tasks to be idempotent from this point forward.
=> Improve resilience of celery tasks

openff/bespokefit/executor/services/qcgenerator/app.py, openff/bespokefit/executor/services/qcgenerator/cache.py, openff/bespokefit/tests/executor/mocking/celery.py, openff/bespokefit/tests/executor/services/qcgenerator/test_app.py, openff/bespokefit/tests/executor/services/qcgenerator/test_cache.py, openff/bespokefit/tests/utilities/test_molecule.py, openff/bespokefit/utilities/molecule.py
This PR adds a simple caching system to the QC generator service whereby the redis backend now tracks a 'task hash -> task id' map.
This can be extended as needed in future to include checks of locally cached QC data stored in QCSubmit result collections.
* This PR adds functions to canonicalize a molecule in a way that preserves the original atom map. These, and the whole `molecule` utility file need to be upstreamed to the TK at some point
=> Add simple caching to QC generator service

openff/bespokefit/executor/executor.py, openff/bespokefit/executor/utilities/celery.py, openff/bespokefit/executor/utilities/redis.py, openff/bespokefit/tests/executor/test_executor.py
This PR attempts to ensure that executor processes are cleaned-up in a more sensible order, namely workers -> gateway -> redis, as both the gateway and workers attempt to connect to redis and hence if that terminates first will raise connection errors.
=> Clean-up executor processes in set order

openff/bespokefit/data/schemas/debug.json, openff/bespokefit/data/schemas/default.json, openff/bespokefit/tests/cli/executor/test_list.py, openff/bespokefit/tests/cli/executor/test_run.py, openff/bespokefit/tests/cli/executor/test_watch.py, openff/bespokefit/tests/executor/test_executor.py, openff/bespokefit/utilities/pydantic.py
This PR updates the base model configs to forbid all extra fields. Allowing extra fields allows certain models to be parsed as the wrong type. An example of this was seen in #88 whereby factories could parse fitting schemas without error.
=> Forbid extra fields on pydantic models

openff/bespokefit/cli/executor/submit.py, openff/bespokefit/tests/cli/executor/test_submit.py
This PR adds a cleaner print-out to the terminal when a user tries to load an invalid workflow factory (see #88)
=> Add informative error when submitting invalid schema

openff/bespokefit/cli/executor/run.py, openff/bespokefit/cli/executor/submit.py, openff/bespokefit/tests/cli/executor/test_submit.py
This PR makes the force field argument passed to the executor CLI, such that it will only overwrite the schema value if provided.
=> Make the CLI force field argument optional

openff/bespokefit/executor/services/coordinator/stages.py
This PR adds clearer error messages for when things go wrong during the executor stages including:
* no fragments were generated for a given molecule
* for some reason no QC data was generated that matches a given target
* an uncaught error is raised
=> Add clearer error messages to executor stages

openff/bespokefit/utilities/molecule.py
When OpenEye is installed, but the license is unavailable, `openff.bespokefit.utilities.molecule.get_atom_symmetries` fails with an extremely confusing error: "This function requires the OpenEye Toolkit". This is because `_oe_get_atom_symmetries` calls the OpenFF Toolkit's `Molecule.to_openeye()`, which raises an error that is not caught by bespokefit. This PR fixes this.
=> Fix get_atom_symmetries with OpenEye installed without license

devtools/conda-envs/test-env.yaml, openff/bespokefit/executor/services/qcgenerator/app.py, openff/bespokefit/executor/services/qcgenerator/worker.py, openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/schema/data.py, openff/bespokefit/schema/tasks.py, openff/bespokefit/tests/conftest.py, openff/bespokefit/tests/executor/services/qcgenerator/test_app.py
This PR adds support for seeding torsion drives with multiple conformers as specified by the task spec now support is added upstream (https://github.com/MolSSI/QCElemental/pull/281, https://github.com/MolSSI/QCEngine/pull/325).
This PR should also fix the CI failures on main.
=> Support seeding torsiondrives with multiple confs

openff/bespokefit/executor/utilities/celery.py
This PR should stop saved celery results from being deleted after 1 day they should now be saved indefinitely.  Previously this would cause any cached stages to hang when trying to find the result in redis after it had been removed.
=> Stop celery result deletion

openff/bespokefit/executor/executor.py, openff/bespokefit/executor/services/coordinator/stages.py, openff/bespokefit/executor/services/coordinator/utils.py, openff/bespokefit/executor/services/optimizer/worker.py, openff/bespokefit/schema/fitting.py, openff/bespokefit/schema/results.py, openff/bespokefit/schema/smirnoff.py, openff/bespokefit/schema/targets.py, openff/bespokefit/tests/executor/services/conftest.py, openff/bespokefit/tests/executor/services/coordinator/test_models.py, openff/bespokefit/tests/executor/services/coordinator/test_utils.py, openff/bespokefit/tests/executor/services/coordinator/test_workers.py, openff/bespokefit/tests/executor/services/optimizer/test_app.py, openff/bespokefit/tests/executor/services/optimizer/test_worker.py, openff/bespokefit/tests/executor/services/test_stages.py, openff/bespokefit/tests/utilities/test_smirks.py, openff/bespokefit/utilities/smirks.py, openff/bespokefit/utilities/smirnoff.py, openff/bespokefit/workflows/bespoke.py
This PR reworks the coordinator stages to allow for torsion parameter caching in redis. 
Parameters are hashed based on:
- initial force field
- smirks generation settings
- optimiser settings
- targets and settings 
- the qc calculation specification
The new workflow:
- molecules are fragmented
- bespoke torsion parameters generated to match the fragment and parent
- parameter cache is checked, reusable parameters are those which match the same atoms in the fragment as the new bespoke pattern. Cached values are then combined with new smirks to ensure the pattern matches the fragment and new parent
- QM jobs for cached parameters are dropped
- workflow continues as normal
=> Parameter cache

docs/getting-started/quick-start.md, docs/users/bespoke-results.md, openff/bespokefit/cli/executor/run.py
This PR adds a new `--output-force-field` argument to the executor `run` CLI as a convenient way to save the bespoke FF in addition to the full result object.
Partially fixes #111
=> Add `--output-force-field` to run CLI

docs/getting-started/quick-start.md, openff/bespokefit/cli/executor/submit.py
This PR moves the input force field argument into a new `Workflow overrides` argument group to make clear that it is overriding an option in the workflow specification.
In future we could consider exposing multiple such arguments, such as overriding the fragmentation scheme or QC method, via the CLI to allow easier experimentation.
=> Move force field CLI arg to 'spec overrides'

openff/bespokefit/cli/executor/run.py, openff/bespokefit/executor/executor.py, openff/bespokefit/executor/services/optimizer/worker.py, openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/optimizers/forcebalance/forcebalance.py, openff/bespokefit/schema/results.py, openff/bespokefit/tests/executor/services/optimizer/test_worker.py
This PR fixes a bug whereby the optimiser stage would incorrectly store a 'refit' force field even after the optimisation errored out. This would ultimately make it look like the bespoke fit succeed even though it failed.
Sneaked in here also is a fix for the semaphore leak caused by `tqdm`.
=> Fix refit force field stored after error

openff/bespokefit/cli/executor/run.py, openff/bespokefit/cli/executor/submit.py, openff/bespokefit/tests/cli/executor/test_submit.py
This PR adds an argument to the `submit` and `run` executor CLI commands that allows users to easily override the `target_torsion_smirks` field of the bespoke workflow factor.
=> Expose bespoke target torsion SMIRKS via CLI

openff/bespokefit/cli/cache.py, openff/bespokefit/cli/executor/list.py, openff/bespokefit/executor/executor.py, openff/bespokefit/executor/services/__init__.py, openff/bespokefit/executor/services/coordinator/app.py, openff/bespokefit/executor/services/coordinator/models.py, openff/bespokefit/executor/services/coordinator/stages.py, openff/bespokefit/executor/services/coordinator/worker.py, openff/bespokefit/executor/services/fragmenter/app.py, openff/bespokefit/executor/services/fragmenter/worker.py, openff/bespokefit/executor/services/gateway.py, openff/bespokefit/executor/services/optimizer/app.py, openff/bespokefit/executor/services/optimizer/worker.py, openff/bespokefit/executor/services/qcgenerator/app.py, openff/bespokefit/executor/services/qcgenerator/worker.py, openff/bespokefit/tests/cli/executor/test_list.py, openff/bespokefit/tests/cli/executor/test_retrieve.py, openff/bespokefit/tests/cli/executor/test_run.py, openff/bespokefit/tests/cli/executor/test_submit.py, openff/bespokefit/tests/cli/executor/test_watch.py, openff/bespokefit/tests/executor/__init__.py, openff/bespokefit/tests/executor/services/test_gateway.py, openff/bespokefit/tests/executor/test_executor.py
This PR replaces the 'dangerous' `settings` field exposed by the bespoke executor with a more reliable function that returns the most up-to-date values.
The object returned by `current_settings()` should not be modified as the changes will have no effect. Instead the `apply_env` context manager should be used e.g.
```python
with Settings(
BEFLOW_FRAGMENTER_WORKER_N_CORES=...,
BEFLOW_FRAGMENTER_WORKER_MAX_MEM=...
).apply_env():
settings = current_settings()
```
Possibly fixes #130
=> Replace `settings` variable with function

docs/getting-started/quick-start.md, openff/bespokefit/cli/executor/run.py, openff/bespokefit/cli/executor/submit.py, openff/bespokefit/tests/cli/executor/test_run.py, openff/bespokefit/tests/cli/executor/test_submit.py
This PR extends the `openff-bespoke executor submit` command to accept and process multiple molecules at once via multiple smiles or input file arguments. Input files may also contain multiple molecules. A formatted table is printed to the terminal and optionally written to a CSV file, which maps the input molecule to an optimization ID and input file if appropriate.
=> Multi-molecule submissions via the CLI

docs/getting-started/quick-start.md, openff/bespokefit/cli/executor/list.py, openff/bespokefit/executor/services/coordinator/app.py, openff/bespokefit/tests/executor/services/coordinator/test_app.py
This PR allows users to more easily filter which optimisations currently have what status when using the `list` executor command.
=> Add option to `list` CLI to filter by status

docs/users/bespoke-results.md, openff/bespokefit/cli/cli.py, openff/bespokefit/cli/combine.py, openff/bespokefit/tests/cli/test_combine.py
This PR extends the CLI with a force field combining tool which allows local force fields retrieved from the bespokefit server and force fields associated with task ids to be combined into a single force field. 
```shell
openff-bespoke combine --output my_ff.offxml --ff bespoke_result.offxml --id 2 --id 3
```
=> Force field combining

openff/bespokefit/schema/smirnoff.py
This PR fixes a copy paste typo on `AngleHyperparameters` whereby the prior currently expects 'length' rather than 'angle'
=> Fix SMIRNOFF angle prior literal validator

docs/getting-started/installation.md
This PR improves the documentation around Psi4 installation by:
=> Update Psi4 installation docs

docs/getting-started/installation.md
Resolves #180
I tried a few commands (only on macOS) and this one was the simplest. `xtb` can be added to the one-liner but as far as I can tell that doesn't change anything.
I stopped at seeing a solved environment from `mamba`, I didn't see if the installation completes or if the software actually runs this way. I'm also assuming the behavior is similar on Linux.
I found it hard to pin down a single license agreement; searching stuff like "MKL license" brought me to a mix of forum threads, licenses from several years ago, and documentation about "oneMKL" which may or may not be the same thing. I understand MKL to be ubiquitous and our users to be smart, so I don't think it's necessary to stuff a bunch of links into the minimal disclaimer I've added here.
Feel free to smith anything up …
=> Update quick start guide with MKL option with XTB

devtools/conda-envs/docs-env.yaml, devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml, openff/bespokefit/exceptions.py, openff/bespokefit/executor/services/coordinator/stages.py, openff/bespokefit/schema/targets.py, openff/bespokefit/tests/schema/test_targets.py
This PR addresses #189 by causing a clear error or warning and appropriately discarding data when the connectivity of the molecule being fitted changes. The goal is for connectivity changes to log a warning and fall back to initial force field parameters.
I'm opening this PR for discussion but it's a work in progress. At the moment it seems to work - SMILES `CCCC` completes successfully while SMILES `[NH3+]CC[O-]` and aminolevulinicacid.sdf from #189 raise the desired exception.
=> Deal with connectivity changes in QC generation

.github/workflows/CI.yaml, .github/workflows/Lint.yaml, devtools/conda-envs/docs-env.yaml, devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml, openff/bespokefit/cli/combine.py, openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/optimizers/forcebalance/forcebalance.py, openff/bespokefit/schema/fitting.py, openff/bespokefit/schema/results.py, openff/bespokefit/tests/conftest.py, openff/bespokefit/tests/executor/services/qcgenerator/test_app.py, openff/bespokefit/tests/executor/services/qcgenerator/test_cache.py, openff/bespokefit/tests/optimizers/forcebalance/test_forcebalance.py, openff/bespokefit/tests/schema/test_results.py, openff/bespokefit/tests/utilities/test_smirks.py, openff/bespokefit/tests/utilities/test_smirnoff.py, openff/bespokefit/utilities/smirks.py, openff/bespokefit/utilities/smirnoff.py
Update BespokeFit to work with new versions of the OpenFF Toolkit
=> Support OpenFF Toolkit v0.11+

.github/workflows/CI.yaml, openff/bespokefit/optimizers/forcebalance/forcebalance.py
This implements @jthorton's suggested fix: https://github.com/openforcefield/openff-bespokefit/issues/216#issuecomment-1387146412
I don't know how to test for this or if any tests are failing on the upstream branch.
=> Better track ForceBalance Failures

.github/workflows/CI.yaml, .gitignore, devtools/conda-envs/docs-env.yaml, devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml, openff/bespokefit/cli/executor/run.py
This is a barebones integration test for CI. It just runs the following fit:
```shell
openff-bespoke executor run --smiles                 'CC'               \
--workflow               'default'          \
--default-qc-spec        xtb gfn2xtb none   \
--target-torsion         '[C:1]-[C:2]'
```
This requires adding `xtb-python` to the test environment.
Integration tests are added to the testing matrix so that existing unit tests don't take longer; instead, there are 4 additional checks. Once I see what the timing is like on this PR, I'll probably adjust this.
This PR partially mitigates #218 but does not close it.
=> Add a barebones integration test to CI

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/USER_SUPPORT.md
Add a question about Apple Silicon and a <details> tag for `conda list` output to the Bug Report and User Support issue templates.
=> Add important information to bug reports

docs/getting-started/installation.md
=> Add h5py shim in installation docs

devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml, docs/users/bespoke-executor.md, openff/bespokefit/cli/cli.py, openff/bespokefit/cli/executor/launch.py, openff/bespokefit/cli/worker.py, openff/bespokefit/executor/services/optimizer/worker.py, openff/bespokefit/executor/utilities/celery.py, openff/bespokefit/executor/utilities/redis.py, openff/bespokefit/tests/cli/executor/test_launch.py, openff/bespokefit/tests/cli/test_worker.py, openff/bespokefit/tests/conftest.py, openff/bespokefit/tests/executor/services/optimizer/test_worker.py, openff/bespokefit/tests/executor/utilities/test_redis.py, openff/bespokefit/utilities/_settings.py
This PR exposes a CLI command to launch a celery worker manually which will try and connect to a bespokefit server. This is useful when the server and workers are not on the same machine. To allow for connections between redis and a celery worker on different machines a password is required which can be configured via the new setting `BEFLOW_REDIS_PASSWORD`.
=> Worker launch CLI

openff/bespokefit/cli/worker.py, openff/bespokefit/executor/services/qcgenerator/qcengine.py, openff/bespokefit/executor/services/qcgenerator/worker.py, openff/bespokefit/executor/utilities/celery.py, openff/bespokefit/tests/cli/test_worker.py
This PR is another go at adding parallel optimisations in torsiondrives. These will only work on workers launched via the new worker CLI #272  option as they have to be in the primary process to spawn a pool of optimisations. 
Local testing with XTB and Psi4 for some simple molecules leads to some good speed-ups with the optimum number of workers being around 4. Note that for the Psi4 test, the number of threads used by each worker was 6 with 4 works and was 8 for 1 and 2 worker tests due to resource limits. 
When testing on the HPC I found that the method to create the pool had to be set to `spawn` rather than `fork` otherwise the optimisations would hang, which causes a slight slowdown in performance should we expose the method used to create the pool as a setting? 
Testing script …
=> Parallel torsiondrive optimisations

openff/bespokefit/executor/services/qcgenerator/worker.py
This PR sets the QC task config to include 3 retries on failed QM single points which should improve the robustness of torsiondrives and optimizations with Psi4. Its recommended that https://github.com/MolSSI/QCEngine/pull/409 be used as well to ensure random failures are restarted. 
=> Retry failed QM single points

devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml, docs/releasehistory.md, openff/bespokefit/executor/services/fragmenter/app.py, openff/bespokefit/tests/conftest.py
Provide a brief description of the PR's purpose here.
=> Update tests to use ForceBalance 1.9.6 and OFFTK 0.14.4

devtools/conda-envs/docs-env.yaml, devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml
There is a new version of QCSubmit out, but BespokeFit hasn't been updated to use it. Until it does - I intend to work on this soon - tests should bring down the version that it works with
=> Constrain to old QCSubmit

docs/getting-started/installation.md
=> Update installation docs

docs/getting-started/installation.md
This PR drops the `conda-forge/label/libint_dev` label which is no longer needed.
=> Use Psi4 1.9 in documentation

.github/workflows/CI.yaml
I added `CODECOV_TOKEN` from https://app.codecov.io/gh/openforcefield/openff-bespokefit/settings to https://github.com/openforcefield/openff-bespokefit/settings/secrets/actions, following what we've done in other projects
=> Set up  API token in uploading coverage reports

docs/getting-started/bespoke-cli.md, docs/users/bespoke-executor.md, openff/bespokefit/utilities/_settings.py
This fixes the documentation of environment variables to control bespoke executor.
Closes #326
=> Repair documentation of environment variables

docs/getting-started/quick-start.md
Updates quickstart guide to clarify that the run-from-API example is expected to be run in jupyter, and provides instructions on how to call from command line instead. 
=> clarify that API example in quickstart expects jupyter notebook and provide command line instructions

devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml
Reverts openforcefield/openff-bespokefit#353
This was a problem with the builds, not RDKit itself. Greg and others identified it and pulled it offline:
https://github.com/conda-forge/rdkit-feedstock/issues/162
https://github.com/conda-forge/admin-requests/pull/1034
=> Revert "Avoid RDKit 2024.03.4"

docs/getting-started/quick-start.md, docs/releasehistory.md, docs/users/bespoke-executor.md, docs/users/bespoke-results.md, openff/bespokefit/_tests/cli/executor/test_list.py, openff/bespokefit/_tests/cli/test_cache.py, openff/bespokefit/_tests/cli/test_worker.py, openff/bespokefit/_tests/executor/test_client.py, openff/bespokefit/_tests/executor/test_executor.py, openff/bespokefit/_tests/schema/test_targets.py, openff/bespokefit/cli/combine.py, openff/bespokefit/cli/executor/list.py, openff/bespokefit/cli/executor/retrieve.py, openff/bespokefit/cli/executor/run.py, openff/bespokefit/cli/executor/submit.py, openff/bespokefit/cli/executor/watch.py, openff/bespokefit/cli/worker.py, openff/bespokefit/executor/__init__.py, openff/bespokefit/executor/client.py, openff/bespokefit/executor/executor.py, openff/bespokefit/executor/services/coordinator/stages.py, openff/bespokefit/executor/services/gateway.py, openff/bespokefit/executor/utilities/celery.py, openff/bespokefit/utilities/_settings.py
This PR introduces a simple bespokefit client which splits out the logic of communicating with the executor. This should make it easier to submit and retrieve calculations from an executor on another machine using the python API similarly to Alchemiscale or QCArchive. To enable this we also expose the `BEFLOW_GATEWAY_ADDRESS` which can be used to provide the location of an executor on another machine which is currently not possible. 
We also introduce some basic authentication which checks that the value of the new setting `BEFLOW_API_TOKEN` matches between the server and the client value before responding to requests. 
These features should make it easier to provide a light weight bespokefit-client package in future for applications which only need to interface with a bespokefit …
=> BespokeFit client

devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml
This brings the OFFTK version pin in this CI back in line with the [conda feedstock version pin](https://github.com/conda-forge/openff-bespokefit-feedstock/blob/main/recipe/meta.yaml#L33)
=> Relax Toolkit version in CI

docs/getting-started/installation.md
Doing `"qcportal <0.50"` will pull down version `0.2.3` of bespokefit
=> Update install steps 

docs/releasehistory.md, openff/bespokefit/optimizers/forcebalance/factories.py
=> Check that `qc_record.extras` exists before accessing it
