devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml, openff/bespokefit/bespoke/__init__.py, openff/bespokefit/bespoke/executor.py, openff/bespokefit/tests/bespoke/test_executor.py
This PR updates the `Executor` classes to make use of the new classes introduced during #14.
=> [GENREF] Update the executor to use new classes

openff/bespokefit/data/templates/force-balance/ab-initio-target.txt, openff/bespokefit/data/templates/force-balance/opt-geo-target.txt, openff/bespokefit/data/templates/force-balance/torsion-profile-target.txt, openff/bespokefit/data/templates/force-balance/vibration-target.txt, openff/bespokefit/schema/targets.py, openff/bespokefit/tests/optimizers/forcebalance/test_templates.py
This PR adds an `extras` field to the target schemas which allow users to specify optimiser specific target options.
=> [GENREF] Add extras field to targets

openff/bespokefit/optimizers/forcebalance/factories.py
The PDB files produced by the OpenFF toolkit are occasionally miss-represented by OpenMM (and hence ForceBalance) which leads to exceptions when fitting. An example of this is Bromine sometimes being interpreted as Boron. To workaround this, this PR switches to using FB to create the PDB files.
=> Use FB to write PDB files

devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml, openff/bespokefit/schema/data.py, openff/bespokefit/workflows/bespoke.py
This PR replaces the pip installed dependencies with the new C-F packages.
=> Use conda-forge test dependencies

devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml, openff/bespokefit/bespoke/__init__.py, openff/bespokefit/bespoke/executor.py, openff/bespokefit/bespoke/utils.py, openff/bespokefit/fragmentation/fragmenter.py, openff/bespokefit/fragmentation/model.py, openff/bespokefit/optimizers/forcebalance/factories.py, openff/bespokefit/optimizers/forcebalance/forcebalance.py, openff/bespokefit/schema/bespoke/bespoke.py, openff/bespokefit/tests/bespoke/test_executor.py, openff/bespokefit/tests/fragmentation/test_fragmentation.py, openff/bespokefit/tests/schema/bespoke/test_smirks.py, openff/bespokefit/tests/utilities/test_smirnoff.py, openff/bespokefit/tests/workflows/test_bespoke.py, openff/bespokefit/utilities/smirnoff.py
This PR changes the print statements in the executor to use logging. I have also added the option to supply target bond SMARTS to the fragment engines.
=> Logger clean up and improvments

devtools/conda-envs/basic.yaml, devtools/conda-envs/xtb.yaml, openff/bespokefit/executor/executor.py, openff/bespokefit/executor/services/coordinator/worker.py, openff/bespokefit/tests/executor/test_executor.py
This PR adds tests of the bespoke executor class.
=> Add bespoke executor tests

openff/bespokefit/executor/executor.py, openff/bespokefit/executor/services/coordinator/worker.py, openff/bespokefit/executor/services/gateway.py
This PR allows the output from a running service gateway to log to file in addition to the terminal.
=> Enable logging gateway output to file

openff/bespokefit/executor/services/coordinator/stages.py, openff/bespokefit/executor/services/models.py, openff/bespokefit/schema/schema.py, openff/bespokefit/schema/tasks.py
This PR ensures all pydantic models are subclasses of the custom base model that defines the numpy array encoder.
=> Ensure all models can serialize numpy

openff/bespokefit/executor/services/coordinator/app.py, openff/bespokefit/executor/services/coordinator/models.py, openff/bespokefit/executor/services/coordinator/worker.py, openff/bespokefit/executor/services/fragmenter/app.py, openff/bespokefit/executor/services/qcgenerator/app.py, openff/bespokefit/tests/executor/services/coordinator/test_app.py, openff/bespokefit/tests/executor/services/fragmenter/test_app.py, openff/bespokefit/tests/executor/services/qcgenerator/test_app.py
This PR adds tests of the coordinator app, as well as adds the missing tests for getting the molecule image from the fragmenter and QC generation apps.
=> Add tests for the coordinator app

devtools/conda-envs/test-env.yaml, openff/bespokefit/executor/__init__.py, openff/bespokefit/executor/executor.py, openff/bespokefit/executor/services/coordinator/worker.py, openff/bespokefit/tests/executor/test_executor.py
This PR adds a new `wait_until_complete` function to the bespoke executor that will log the status of an optimisation, handle any errors while checking the status, and ultimately return the result to a user when finished.
=> Add wait until finished function to executor

openff/bespokefit/executor/services/coordinator/app.py, openff/bespokefit/executor/services/coordinator/models.py, openff/bespokefit/executor/services/coordinator/stages.py, openff/bespokefit/executor/services/fragmenter/app.py, openff/bespokefit/executor/services/fragmenter/models.py, openff/bespokefit/executor/services/models.py, openff/bespokefit/executor/services/optimizer/app.py, openff/bespokefit/executor/services/optimizer/models.py, openff/bespokefit/executor/services/qcgenerator/app.py, openff/bespokefit/executor/services/qcgenerator/models.py, openff/bespokefit/executor/services/settings.py, openff/bespokefit/tests/executor/services/coordinator/test_app.py, openff/bespokefit/tests/executor/services/coordinator/test_models.py, openff/bespokefit/tests/executor/services/fragmenter/test_app.py, openff/bespokefit/tests/executor/services/optimizer/test_app.py, openff/bespokefit/tests/executor/services/qcgenerator/test_app.py, openff/bespokefit/tests/executor/services/test_gateway.py, openff/bespokefit/tests/executor/services/test_models.py, openff/bespokefit/tests/executor/test_executor.py
This PR cleans-up the interface exposed by the executors RESTful API, including links to relevant resources and a 'proper' pagination response.
=> Clean-up the executor RESTful API

devtools/conda-envs/test-env.yaml
This PR updates the CI to use the new QCEngine version that supports torsion drive procedures.
=> Use C-F QCEngine with TD support

openff/bespokefit/executor/services/fragmenter/app.py, openff/bespokefit/executor/services/fragmenter/cache.py, openff/bespokefit/tests/executor/services/fragmenter/test_app.py, openff/bespokefit/tests/executor/services/fragmenter/test_cache.py
This PR adds a simple fragmentation cache based on the fixed hydrogen inchi key of the molecule meaning it should be independent of the ordering of the molecule.
=> Fragmentation cache

.github/workflows/CI.yaml, .github/workflows/Lint.yaml, README.md
This PR supplements the renaming of the master branch to main
=> Rename references to master

openff/bespokefit/tests/workflows/test_bespoke.py, openff/bespokefit/workflows/bespoke.py
Implements #98 to make the API clearer.
=> Rename `export_factory` -> `to_file`

openff/bespokefit/cli/executor/run.py, openff/bespokefit/cli/executor/submit.py, openff/bespokefit/tests/cli/executor/test_run.py, openff/bespokefit/tests/cli/executor/test_submit.py
This PR implements #99 allowing the use of smiles strings to submit and run molecules through the executor CLI.
=> Add `--smiles` to CLI 

devtools/conda-envs/test-env.yaml
This PR temporarily pins the toolkit to avoid incompatibility with ForceBalance
=> Temporary pin OpenFF toolkit to fix CI

openff/bespokefit/cli/cache.py, openff/bespokefit/cli/executor/launch.py, openff/bespokefit/cli/executor/run.py, openff/bespokefit/cli/executor/submit.py, openff/bespokefit/executor/services/_settings.py, openff/bespokefit/executor/services/coordinator/app.py, openff/bespokefit/executor/services/coordinator/stages.py, openff/bespokefit/executor/services/coordinator/storage.py, openff/bespokefit/executor/services/coordinator/worker.py, openff/bespokefit/executor/services/fragmenter/app.py, openff/bespokefit/executor/services/fragmenter/worker.py, openff/bespokefit/executor/services/optimizer/worker.py, openff/bespokefit/executor/services/qcgenerator/app.py, openff/bespokefit/executor/services/qcgenerator/worker.py, openff/bespokefit/executor/utilities/redis.py, openff/bespokefit/tests/cli/executor/test_launch.py, openff/bespokefit/tests/conftest.py, openff/bespokefit/tests/executor/services/coordinator/test_app.py, openff/bespokefit/tests/executor/services/coordinator/test_storage.py, openff/bespokefit/tests/executor/services/coordinator/test_workers.py, openff/bespokefit/tests/executor/utilities/test_redis.py
This PR:
* abstracts the coordinator <-> redis interface into own its module
* fixes a gateway hanging error when processing many tasks due to async congestion
* adds safety checks to ensure version compatibility
* adds user-friendly messages when possible redis issues are encountered
=> Overhaul executor <-> redis interface

docs/getting-started/installation.md
This PR adds installation instructions for XTB to the installation docs.
=> Add XTB to optional dependencies docs

docs/getting-started/installation.md
Add torchani install instructions to the quick start guide.
=> ANI install instructions

openff/bespokefit/schema/optimizers.py
This PR allows single type jobs using the Forcebalance optimiser as an easy way to do large single point evaluations of the objective function. This is useful when evaluating the performance of a force field without optimisation.
=> Support single FB jobs

openff/bespokefit/executor/services/qcgenerator/cache.py, openff/bespokefit/executor/services/qcgenerator/worker.py
This PR alters PR #167 such that torsion drive optimisation and single point evaluation caching is handled by celery directly.
=> Split torsion drive single-points into separate tasks

docs/getting-started/installation.md
=> Update Psi4 installation instructions

docs/users/theory.md
Provide a brief description of the PR's purpose here.
missing white space
=> minor typo in thoery.md

openff/bespokefit/tests/executor/services/qcgenerator/test_worker.py
=> Add test for XTB verbosity

devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml, openff/bespokefit/tests/executor/services/qcgenerator/test_worker.py, openff/bespokefit/utilities/molecule.py
Trying to get the failing integration test to pass based on observations in #218 
=>  Integration fixes

docs/releasehistory.md
Update release notes for v0.2.1
=> Update release notes for v0.2.1

docs/conf.py, docs/getting-started/installation.md
Add a link to the ecosystem install guide to the BespokeFit install guide
=> Link to ecosystem install guide

.github/workflows/CI.yaml
=> Update Python versions in tests

.github/workflows/CI.yaml, .github/workflows/installer.yml
Provide a brief description of the PR's purpose here.
=> Switch to `setup-micromamba`

devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml
=> Fix #283 by pinning anyio<4

docs/getting-started/installation.md
I neglected to look at the docs rendered in #299
=> Fix rendering

devtools/conda-envs/docs-env.yaml, devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml
=> Update test environments

devtools/conda-envs/docs-env.yaml, devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml
=> Pin QCPortal to 0.53

.github/workflows/CI.yaml
[try updating CI with fix from](https://github.com/openforcefield/openff-fragmenter/pull/181/commits/5c6b69b7a9dae00ce1c4c8f66786771510211cfb) https://github.com/openforcefield/openff-utilities/issues/77
=> Fix CI failures by changing micromamba action settings

devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml
https://github.com/openforcefield/openff-bespokefit/pull/337
https://github.com/openforcefield/openff-bespokefit/issue/336
=> try latest qcf

devtools/conda-envs/docs-env.yaml, devtools/conda-envs/no_openeye.yaml, devtools/conda-envs/test-env.yaml
Resolves https://github.com/openforcefield/openff-bespokefit/issues/362
=> Attempt to fix CI by downpinning away from rdkit 2024.03.6
